{
 "title": "Cmon dashboard",
 "description": "Cmon",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "BAACTW02",
   "type": "timeseries",
   "description": "BAACTW02",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"BAACTW02\")\r\n  |> range(start: -30m, stop: now())  // แสดงข้อมูล ณ เวลา ปัจจุบับ ย้อน ไป 1 นาที่\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"temperature\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> limit(n:1000, offset: 0)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "BAACTW03",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"BAACTW03\")\r\n  |> range(start: -30m, stop: now())  // แสดงข้อมูล ณ เวลา ปัจจุบับ ย้อน ไป 1 นาที่\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"temperature\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> limit(n:1000, offset: 0)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "BAACTW04",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"BAACTW04\")\r\n  |> range(start: -30m, stop: now())  // แสดงข้อมูล ณ เวลา ปัจจุบับ ย้อน ไป 1 นาที่\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"temperature\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> limit(n:1000, offset: 0)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "BAACTW05",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"BAACTW05\")\r\n  |> range(start: -30m, stop: now())  // แสดงข้อมูล ณ เวลา ปัจจุบับ ย้อน ไป 1 นาที่\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"temperature\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> limit(n:1000, offset: 0)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "BAACTW06",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"BAACTW06\")\r\n  |> range(start: -30m, stop: now())  // แสดงข้อมูล ณ เวลา ปัจจุบับ ย้อน ไป 1 นาที่\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"temperature\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> limit(n:1000, offset: 0)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "BAACTW07",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"BAACTW07\")\r\n  |> range(start: -30m, stop: now())  // แสดงข้อมูล ณ เวลา ปัจจุบับ ย้อน ไป 1 นาที่\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"temperature\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> limit(n:1000, offset: 0)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "BAACTW08",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"BAACTW08\")\r\n  |> range(start: -30m, stop: now())  // แสดงข้อมูล ณ เวลา ปัจจุบับ ย้อน ไป 1 นาที่\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"temperature\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> limit(n:1000, offset: 0)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "BAACTW09",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"BAACTW09\")\r\n  |> range(start: -30m, stop: now())  // แสดงข้อมูล ณ เวลา ปัจจุบับ ย้อน ไป 1 นาที่\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"temperature\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> limit(n:1000, offset: 0)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "BAACTW02",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"BAACTW02\")\r\n  |> range(start: -30s, stop: now())  // แสดงข้อมูล ณ เวลา ปัจจุบับ ย้อน ไป 1 นาที่\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"temperature\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> limit(n:1, offset: 0)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "BAACTW03",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"BAACTW03\")\r\n  |> range(start: -30s, stop: now())  // แสดงข้อมูล ณ เวลา ปัจจุบับ ย้อน ไป 1 นาที่\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"temperature\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> limit(n:1, offset: 0)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "BAACTW04",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"BAACTW04\")\r\n  |> range(start: -30s, stop: now())  // แสดงข้อมูล ณ เวลา ปัจจุบับ ย้อน ไป 1 นาที่\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"temperature\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> limit(n:1, offset: 0)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "BAACTW05",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"BAACTW05\")\r\n  |> range(start: -30s, stop: now())  // แสดงข้อมูล ณ เวลา ปัจจุบับ ย้อน ไป 1 นาที่\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"temperature\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> limit(n:1, offset: 0)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "BAACTW06",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"BAACTW06\")\r\n  |> range(start: -30s, stop: now())  // แสดงข้อมูล ณ เวลา ปัจจุบับ ย้อน ไป 1 นาที่\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"temperature\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> limit(n:1, offset: 0)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "BAACTW07",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"BAACTW07\")\r\n  |> range(start: -30s, stop: now())  // แสดงข้อมูล ณ เวลา ปัจจุบับ ย้อน ไป 1 นาที่\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"temperature\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> limit(n:1, offset: 0)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "BAACTW08",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"BAACTW08\")\r\n  |> range(start: -30s, stop: now())  // แสดงข้อมูล ณ เวลา ปัจจุบับ ย้อน ไป 1 นาที่\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"temperature\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> limit(n:1, offset: 0)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "BAACTW09",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"BAACTW09\")\r\n  |> range(start: -30s, stop: now())  // แสดงข้อมูล ณ เวลา ปัจจุบับ ย้อน ไป 1 นาที่\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"temperature\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> limit(n:1, offset: 0)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "BAACTW02",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"BAACTW02\")\r\n  |> range(start: -15s, stop: now())\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ActRelay1\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\"  or(r[\"_field\"] == \"value\" and r[\"_value\"] != \"0.5\"))\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> limit(n:1, offset: 0)\r\n  |> yield(name: \"last\")\r\n"
    }
   ]
  },
  {
   "title": "BAACTW03",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"BAACTW03\")\r\n  |> range(start: -15s, stop: now())\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ActRelay1\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\"  or(r[\"_field\"] == \"value\" and r[\"_value\"] != \"0.5\"))\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> limit(n:1, offset: 0)\r\n  |> yield(name: \"last\")\r\n"
    }
   ]
  },
  {
   "title": "BAACTW04",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"BAACTW04\")\r\n  |> range(start: -15s, stop: now())\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ActRelay1\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\"  or(r[\"_field\"] == \"value\" and r[\"_value\"] != \"0.5\"))\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> limit(n:1, offset: 0)\r\n  |> yield(name: \"last\")\r\n"
    }
   ]
  },
  {
   "title": "BAACTW05",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"BAACTW05\")\r\n  |> range(start: -15s, stop: now())\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ActRelay1\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\"  or(r[\"_field\"] == \"value\" and r[\"_value\"] != \"0.5\"))\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> limit(n:1, offset: 0)\r\n  |> yield(name: \"last\")\r\n"
    }
   ]
  },
  {
   "title": "BAACTW06",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"BAACTW06\")\r\n  |> range(start: -15s, stop: now())\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ActRelay1\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\"  or(r[\"_field\"] == \"value\" and r[\"_value\"] != \"0.5\"))\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> limit(n:1, offset: 0)\r\n  |> yield(name: \"last\")\r\n"
    }
   ]
  },
  {
   "title": "BAACTW07",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 10, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"BAACTW07\")\r\n  |> range(start: -15s, stop: now())\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ActRelay1\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\"  or(r[\"_field\"] == \"value\" and r[\"_value\"] != \"0.5\"))\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> limit(n:1, offset: 0)\r\n  |> yield(name: \"last\")\r\n"
    }
   ]
  },
  {
   "title": "BAACTW08",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"BAACTW08\")\r\n  |> range(start: -15s, stop: now())\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ActRelay1\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\"  or(r[\"_field\"] == \"value\" and r[\"_value\"] != \"0.5\"))\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> limit(n:1, offset: 0)\r\n  |> yield(name: \"last\")\r\n"
    }
   ]
  },
  {
   "title": "BAACTW09",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 14, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"BAACTW09\")\r\n  |> range(start: -15s, stop: now())\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ActRelay1\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\"  or(r[\"_field\"] == \"value\" and r[\"_value\"] != \"0.5\"))\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> limit(n:1, offset: 0)\r\n  |> yield(name: \"last\")\r\n"
    }
   ]
  },
  {
   "title": "BAACTW10",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 16, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"BAACTW10\")\r\n  |> range(start: -15s, stop: now())\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ActRelay1\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\"  or(r[\"_field\"] == \"value\" and r[\"_value\"] != \"0.5\"))\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> limit(n:1, offset: 0)\r\n  |> yield(name: \"last\")\r\n"
    }
   ]
  },
  {
   "title": "BAACTW11",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 18, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"BAACTW11\")\r\n  |> range(start: -15s, stop: now())\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ActRelay1\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\"  or(r[\"_field\"] == \"value\" and r[\"_value\"] != \"0.5\"))\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> limit(n:1, offset: 0)\r\n  |> yield(name: \"last\")\r\n"
    }
   ]
  },
  {
   "title": "BAACTW12",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 20, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"BAACTW12\")\r\n  |> range(start: -15s, stop: now())\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ActRelay1\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\"  or(r[\"_field\"] == \"value\" and r[\"_value\"] != \"0.5\"))\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> limit(n:1, offset: 0)\r\n  |> yield(name: \"last\")\r\n"
    }
   ]
  },
  {
   "title": "BAACTW13",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"BAACTW13\")\r\n  |> range(start: -15s, stop: now())\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ActRelay1\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\"  or(r[\"_field\"] == \"value\" and r[\"_value\"] != \"0.5\"))\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> limit(n:1, offset: 0)\r\n  |> yield(name: \"last\")\r\n"
    }
   ]
  },
  {
   "title": "BAACTW10",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"BAACTW10\")\r\n  |> range(start: -3m, stop: now())  // แสดงข้อมูล ณ เวลา ปัจจุบับ ย้อน ไป 1 นาที่\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"temperature\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> limit(n:1000, offset: 0)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "BAACTW12",
   "type": "barchart",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"BAACTW12\")\r\n  |> range(start: -3m, stop: now())  // แสดงข้อมูล ณ เวลา ปัจจุบับ ย้อน ไป 1 นาที่\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"temperature\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> limit(n:1000, offset: 0)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "BAACTW13",
   "type": "barchart",
   "gridPos": { "h": 4, "w": 5, "x": 10, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"BAACTW13\")\r\n  |> range(start: -3m, stop: now())  // แสดงข้อมูล ณ เวลา ปัจจุบับ ย้อน ไป 1 นาที่\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"temperature\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> limit(n:1000, offset: 0)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "BAACTW14",
   "type": "table",
   "gridPos": { "h": 4, "w": 5, "x": 15, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"BAACTW14\")\r\n  |> range(start: -3m, stop: now())  // แสดงข้อมูล ณ เวลา ปัจจุบับ ย้อน ไป 1 นาที่\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"temperature\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> limit(n:1000, offset: 0)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "BAACTW15",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"BAACTW15\")\r\n  |> range(start: -3m, stop: now())  // แสดงข้อมูล ณ เวลา ปัจจุบับ ย้อน ไป 1 นาที่\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"temperature\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> limit(n:1000, offset: 0)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "BAACTW11",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"BAACTW11\")\r\n  |> range(start: -2h, stop: now())  // แสดงข้อมูล ณ เวลา ปัจจุบับ ย้อน ไป 1 นาที่\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"temperature\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> limit(n:1000, offset: 0)\r\n  |> yield(name: \"last\")"
    }
   ]
  }
 ]
}